"""rating table

Revision ID: 3c558226c6ea
Revises: 8a81877c0a3c
Create Date: 2023-01-17 17:59:33.617756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c558226c6ea'
down_revision = '8a81877c0a3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
