"""Add Audio link

Revision ID: 3c712bde2f34
Revises: 65da1cc7a2c8
Create Date: 2022-12-24 16:26:11.202170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c712bde2f34'
down_revision = '65da1cc7a2c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('audio_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'audio_link')
    # ### end Alembic commands ###
