"""Add human_feedback table

Revision ID: 68f905fa2519
Revises: 7916fdb03dc5
Create Date: 2022-11-26 19:20:19.831039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f905fa2519'
down_revision = '7916fdb03dc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
