"""Add human feedback timestamp

Revision ID: 74c0833dc05c
Revises: 68f905fa2519
Create Date: 2022-12-20 19:17:25.401102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c0833dc05c'
down_revision = '68f905fa2519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_to_last_human_feedback_timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'second_to_last_human_feedback_timestamp')
    # ### end Alembic commands ###
