"""Add UserInfo table

Revision ID: 750c20eb6086
Revises: b3a73a159d36
Create Date: 2022-12-29 20:00:45.405217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c20eb6086'
down_revision = 'b3a73a159d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
