"""add medal table

Revision ID: 8a81877c0a3c
Revises: ad6b140166e3
Create Date: 2023-01-17 13:41:58.607578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a81877c0a3c'
down_revision = 'ad6b140166e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
