"""Add PronunciationMatch

Revision ID: ad6b140166e3
Revises: 750c20eb6086
Create Date: 2023-01-01 04:04:11.663761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6b140166e3'
down_revision = '750c20eb6086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
