"""Add display_name to User

Revision ID: b3a73a159d36
Revises: c465eacaa24c
Create Date: 2022-12-26 01:52:23.284268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a73a159d36'
down_revision = 'c465eacaa24c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
