"""Add Audio link default

Revision ID: c465eacaa24c
Revises: 3c712bde2f34
Create Date: 2022-12-24 16:26:57.651998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c465eacaa24c'
down_revision = '3c712bde2f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
